import 'package:flutter/material.dart';

// *** COLORS ***
// Website
Color bannerBlue = Color.fromARGB(255, 122, 173, 214);

// For Countries
Color standard = Color.fromARGB(255, 156, 156, 156);
Color unknown = Color.fromARGB(255, 50, 50, 50); // Dark-grey by default

Color green = Color.fromARGB(255, 92, 129, 95);
Color yellow = Color.fromARGB(255, 219, 169, 94);
Color red = Color.fromARGB(255, 166, 60, 60);

// *** FOR SEARCHABLE JOB TITLES ***
final List<String> searchableJobTitles = [ 
  "Actor",
  "Ad Campaign Manager",
  "Ad Operations Specialist",
  "AI Engineer",
  "AI Researcher",
  "Android Developer",
  "API Developer",
  "Artist",
  "Augmented Reality Developer",
  "Backend Developer",
  "Bailiff",
  "Bartender",
  "BI Developer",
  "Big Data Engineer",
  "Bioinformatics Analyst",
  "Blockchain Developer",
  "Business Analyst",
  "Business Development Manager",
  "Business Intelligence Analyst",
  "Carpenter",
  "Cashier",
  "Chef",
  "Chiropractor",
  "Clinical Researcher",
  "Cloud Architect",
  "Cloud Consultant",
  "Cloud Engineer",
  "Cloud Solutions Consultant",
  "Computer Systems Analyst",
  "Construction Worker",
  "Content Strategist",
  "Content Writer",
  "Conversion Rate Optimizer",
  "Court Clerk",
  "Court Interpreter",
  "Criminologist",
  "CRM Consultant",
  "Cybersecurity Analyst",
  "Data Analyst",
  "Database Administrator",
  "Data Engineer",
  "Data Governance Specialist",
  "Data Scientist",
  "Data Scientist Intern",
  "Data Warehouse Developer",
  "Delivery Driver",
  "Delivery Manager",
  "Dentist",
  "Detective",
  "Developer",
  "DevOps Engineer",
  "DevSecOps Engineer",
  "Dietitian",
  "Digital Marketer",
  "Digital Transformation Consultant",
  "Doctor",
  "Driver",
  "E-commerce Specialist",
  "Electrician",
  "Elementary School Teacher",
  "Email Marketing Specialist",
  "Embedded Systems Engineer",
  "Enterprise Architect",
  "ERP Consultant",
  "Ethical Hacker",
  "Event Planner",
  "Farmer",
  "Firefighter",
  "Firmware Engineer",
  "Flight Attendant",
  "Florist",
  "Forensic Scientist",
  "Frontend Developer",
  "Full Stack Developer",
  "Game Designer",
  "Game Developer",
  "Game Tester",
  "Gardener",
  "Graphic Designer",
  "Gynecologist",
  "Hardware Engineer",
  "Helpdesk Technician",
  "High School Teacher",
  "Information Security Analyst",
  "Information Systems Manager",
  "Information Technology Manager",
  "iOS Developer",
  "IoT Developer",
  "IT Analyst",
  "IT Auditor",
  "IT Consultant",
  "IT Project Coordinator",
  "IT Support Specialist",
  "IT Trainer",
  "Janitor",
  "Judge",
  "Kindergarten Teacher",
  "Lawyer",
  "Legal Assistant",
  "Librarian",
  "Lifeguard",
  "Logistics Manager",
  "Machine Learning Engineer",
  "Mechanic",
  "Medical Assistant",
  "Midwife",
  "Mobile App Developer",
  "Mobile Architect",
  "Musician",
  "Network Administrator",
  "Network Engineer",
  "Network Security Specialist",
  "Nurse",
  "Nutritionist",
  "Occupational Therapist",
  "Orthodontist",
  "Paralegal",
  "Paramedic",
  "Pediatrician",
  "Penetration Tester",
  "Personal Trainer",
  "Pharmacist",
  "Photographer",
  "Physiotherapist",
  "Pilot",
  "Plumber",
  "Police Officer",
  "Probation Officer",
  "Product Manager",
  "Product Owner",
  "Project Manager",
  "Psychiatrist",
  "Psychologist",
  "Quality Assurance Engineer",
  "Quantitative Analyst",
  "Radiologist",
  "Real Estate Agent",
  "Receptionist",
  "Release Manager",
  "Research Scientist",
  "Robotics Engineer",
  "Salesforce Developer",
  "SAP Consultant",
  "Scrum Master",
  "Security Engineer",
  "SEO Specialist",
  "Site Reliability Engineer",
  "Social Media Manager",
  "Software Architect",
  "Software Developer",
  "Software Development Manager",
  "Software Engineer",
  "Software Test Engineer",
  "Solutions Architect",
  "Special Education Teacher",
  "Store Manager",
  "Surgeon",
  "System Administrator",
  "Technical Lead",
  "Technical Program Manager",
  "Technical Recruiter",
  "Technical Support Engineer",
  "Technical Writer",
  "Technology Evangelist",
  "Test Automation Engineer",
  "Tour Guide",
  "Travel Agent",
  "UI/UX Designer",
  "Veterinarian",
  "Virtual Reality Developer",
  "Waiter",
  "Warehouse Worker",
  "Web Content Manager",
  "Web Developer",
  "Writer",
];


